### ISSUE TITLE
[tracking] AMO issues on prod

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1244]
This is for tracking issues that split down into four main categories.

* [x] Slow or dropping celery queries causing problems with upload and then validation
* [x] Slow database writes causing slow updates of versions and files
* [x] Lack of transactions causing incomplete and corrupted data
* [x] Front end security, CSP and similar

There are probably more issues, but these are the four big categories we are trying to track, some of which have really come to light with the move to AWS. 

This bug partially exists so we can get all our other bugs under control.

Please don't just add any issue to this bug unless it focused on trying to solve one of the above problems and is actionable.

**Comment by andymckay** [comment]
Removing jquery 1.9 tracker: #1197

**Comment by andymckay** [comment]
All these issues are now closed apart from the statistics clean up which we still need to do, but that has a seperate tracker.
