### ISSUE TITLE
remove/reimplement all non-django-admin views under /admin

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12903]
our current admin dashboard in /admin is bundle of ancient tools that do certain adminy things; plus there's a link to the django model admin. Lets drop all of the ancient tooling and if we do need that functionality still, reimplement it in django admin views.

Tools:
* [x] addon search #15292
* [x] user search #15292
* [x] addon manage #8410, #15234
* [x] Featured add-ons  (should be obsolete, but featured add-on support is still in the codebase)
* [x] Fake mail #12994
* [x] view site settings #15232
* [x] view request environment #15232
* [x] manage elasticsearch #15232
* [x] hidden/unlinked views #15296
  * fix-disabled
  * download upload file
* [ ] landing page #15310

(excluding links in the header to tools already implemented in django admin views, like Replacement Add-ons)

**Comment by eviljeff** [comment]
@diox are:
- /admin/elastic/
- /admin/env/
- /admin/settings/

still used?  I can't remember ever checking them locally (or on dev/stage)

**Comment by diox** [comment]
I've used all 3 in the past couple months... once each. But generally they are not *that* useful (ops can give similar info) and we could remove them.
