### ISSUE TITLE
Enable uploading of images for the primary hero

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#14471]
This is a tracking issue for the work required to enable uploading of images for the primary hero on the AMO home page.

Sub-issues include:

- [x] [Add a button to upload an image to the primary hero image folder](https://github.com/mozilla/addons-server/issues/14472)
- [x] [Add code to resize and otherwise adjust images uploaded via the admin](https://github.com/mozilla/addons-server/issues/14475)
- [x] [Delete PrimaryHeroImages files when instance is deleted](https://github.com/mozilla/addons-server/issues/14729)
- [x] [Adjust the hero API code to deliver uploaded images](https://github.com/mozilla/addons-server/issues/14473)
- [x] [Move the existing primary hero images into the same location as uploaded images](https://github.com/mozilla/addons-server/issues/14474)
- [x] [Remove previous featured hero images](https://github.com/mozilla/addons-server/issues/15176)
Any other new issues opened can be added to this list.

**Comment by eviljeff** [comment]
I believe this is all finished!  
(please link-to/file follow-up issues if not true)
