### ISSUE TITLE
Reorder/change shelves below hero area

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-server#14871]
This is a tracking issue for the work required to enable the ability to reorder or change the shelves below the hero area on the AMO homepage. These shelves can be for collections, categories, or a set of predefined extensions and themes based on query data (such as Recommended Extensions, popular, trending).

Sub-issues include:
- [x] [Add the ability to create, update, and delete shelves](https://github.com/mozilla/addons-server/issues/14872)
- [x] [Add validations to Shelf model](https://github.com/mozilla/addons-server/issues/14952)
- [x] [Update shelf model/form](https://github.com/mozilla/addons-server/issues/15202)
- [x] [Multiple Homepage shelves can occupy the same shelf Position at the same time](https://github.com/mozilla/addons-server/issues/15309)
- [x] [The /shelfmodule/add/ page throws a 500 error if the Endpoint is not specified](https://github.com/mozilla/addons-server/issues/15282)
- [x] [500 error is received when the criteria is left empty](https://github.com/mozilla/addons-server/issues/15332)
- [x] [Internal server error when using slash in the criteria field with the collection endpoint](https://github.com/mozilla/addons-server/issues/15334)
- [x] [Add the ability to reorder or change the shelves](https://github.com/mozilla/addons-server/issues/14874)
- [x] [Build an API endpoint for shelves](https://github.com/mozilla/addons-server/issues/14873)
- [x] [Include the contents of the shelves in the API](https://github.com/mozilla/addons-server/issues/15284)
- [x] [Include add-ons based on the collections endpoint/criteria in the homepage shelves API](https://github.com/mozilla/addons-server/issues/15614)
- [x] [Add API documentation for homepage shelves](https://github.com/mozilla/addons-server/issues/15615)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-41
