### ISSUE TITLE
Remove `platform` from `File`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16448]
https://github.com/mozilla/addons-server/issues/8752 removed the possibility to specify a `platform` (Operating System) at upload time. There shouldn't be a need to filter search by a specific platform (we can still filter for an _application_ like Firefox for Android) anymore, so we should remove that functionality. The steps to do that would be:
- [x] [Remove ability to filter from the API](https://github.com/mozilla/addons-server/issues/16463)
- [x]  [Remove ability to filter from the frontend](https://github.com/mozilla/addons-frontend/issues/10047)
- [x] [Remove extra files for each version](https://github.com/mozilla/addons-server/issues/16464)
- [x] [Ignore `platform` in files returned by the API in the frontend](https://github.com/mozilla/addons-frontend/issues/10117) 
- [x] [Remove `platform` field from API v5, shim it in previous versions
](https://github.com/mozilla/addons-server/issues/16466)
- [x] [Remove the `platform` field from the `Files` model](https://github.com/mozilla/addons-server/issues/16740)
- [ ] Remove the `platform` column from the database entirely

Follow-up bonus once we're done: https://github.com/mozilla/addons-server/issues/16465

**Comment by bobsilverberg** [comment]
Is this going to include changing the API to only return a single file for a given `version`, as opposed to now where we are returning a array of `files`? If so, we should add a step to update the frontend to deal with that.

**Comment by diox** [comment]
Eventually, but that'd be for the even longer term once everything else is cleaned up. It would also be nice on the addons-server internals (tired of looping over `<Version>.all_files`...)

**Comment by ioanarusiczki** [comment]
@diox If this needs qa, please add str.
