### ISSUE TITLE
django3.2 blockers

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16493]
#16405 dealt with some problems identified from reading release notes, and getting the majority of the tests running in CI.  This issue will track the remaining blockers

* [x] django3.2 is actually released 😄 
* [x] failing tests in the ES job caused by faulty teardown in `TestIndexCommand` #16492
* [x] settings.LANGUAGES needs to be a list of tuples #16479
* [x] change constraint&index names to be unique across models (or bypass check) #16497
* [x] enable django3.2 on addons-dev #17449
* ? (add to as we test and investigate more)

**Comment by eviljeff** [comment]
we deployed django3.2 a few weeks back and have already removed support for earlier versions of django so calling this done!
