### ISSUE TITLE
Clean up the legacy API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#1680]
We need to clean up the mess that is the legacy API.

That API, written using piston and custom code, is used by Firefox in about:addons and is [lightly documented](https://developer.mozilla.org/en-US/Add-ons/AMO/Add-ons_manager_API). However, that documentation is incomplete - it does not cover authentication for instance, and therefore write/delete operations. Furthermore, some of the endpoints that are documented or even [implemented in Firefox](https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/internal/AddonRepository.jsm) appear to be unused.

On top of that we have a DRF port of the API, which according to unit tests should be 100% compatible with the piston version, but it's behind a waffle that was never enabled in prod.

The plan:
- [x] #1715 Figure out whether the parts behind auth are still used (DELETE / POST / PUT)
- [x] #1721 Figure out if all other GET endpoints are still useful, and whether we can remove some
- [x] ~~Figure out a test plan to test that the DRF version works fine and execute it~~
- [x] #1729 Remove the endpoints we don't need as well as the DRF code
- [x] #1728 Remove piston database tables
- [x] #1737 Find a way to isolate the legacy API in the code

**Comment by andymckay** [comment]
See also: https://waffle.io/mozilla/addons?label=API

**Comment by yash14123** [comment]
I would like to take this up if its open. Also would prefer having separate issues for each task. :)

**Comment by diox** [comment]
This is not a good first bug at all, I would recommend you pick something else.

**Comment by diox** [comment]
FWIW I've got a branch for the last part, which is still WIP and not useful until we figured out exactly what we can remove and tested the DRF code, but I'm linking to it so that we don't forget that it exists when we get to the last task to remove the code we no longer need : https://github.com/diox/olympia/tree/remove-piston
