### ISSUE TITLE
Implement new API for internal search

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#1744]
We need an API for the [new internal search tool](https://wiki.mozilla.org/Add-ons/Projects/InternalSearch) we're building. All the front-end will be done in [addons-frontend](https://github.com/mozilla/addons-frontend/) in react, [addons-server](https://github.com/mozilla/addons-server/) will just serve the API.

The code will have to be written almost from scratch - current search code is based around cache-machine, to the point that ES is only used to return ids that are then fetched using cache-machine + mysql. We want to avoid that and stay in pure ES, and figure out scaling later (either by scaling ES itself or adding dumb caching).

The plan:
- [x] #1772 Set up a very basic search API using elasticsearch_dsl, that only goes through public add-ons at first. (i.e. add a basic view and basic serializer that don't do much yet)
- [x] #1816 Add query-related features (search by slug, by guid, by id, by name etc)
- [x] #1961 Do indexing/mapping related cleanups at this point (Done early because it became necessary to add new fields)
- [x] #1817 Add serializer-related features (be able to display all fields we need to)
- [x] #1818 Add basic detail view
- [x] #2026  Add sorting to the search API
- [x] #1859 Add authentication
- [x] #1914 Build the actual internal search tool. Behind auth, able to return deleted or disabled add-ons and not just public ones.
- [x] #2298 Tweak detail API to allow admins to access deleted/disabled/non-public add-ons.

**Comment by diox** [comment]
Going to close this, the base API is here, I'll file new issues for extra tweaks.
