### ISSUE TITLE
Remove `docs` job from CircleCI now that we have a GitHub Action for that

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#22093]
As part of https://github.com/mozilla/addons-server/issues/21932 we added a GitHub action to build docs. That means the `docs` job in CircleCI is entirely obsolete now and we should remove it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-789)

```[tasklist]
### Tasks
- [ ] remove circleCI docs job
- [ ] Migrate docs github action workflow to docker container build
- [ ] Remove readthedocs configurations
```

**Comment by KevinMind** [comment]
We should also migrate the github action docs build job to the docker container version. I have a commit for that I can open a PR.

**Comment by diox** [comment]
> Finally, we should remove the configs for readthedocs from our repository.

I guess it's fine since we're no longer automatically triggering builds via webhook, but do we need to keep some configuration in place for the redirects to work ?
