### ISSUE TITLE
Add support for Chrome WebExtensions

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2579]
Our plan this quarter is to be able to accept Chrome Extensions with minimal (or, maybe, _zero_ changes) to the Chrome Extension.

To test the progress of this feature I'll keep trying to submit https://github.com/mdn/webextensions-examples/tree/master/tabs-tabs-tabs (https://chrome.google.com/webstore/detail/tabs-tabs-tabs/lfghbpgjjckjlanhgbceadmgakgfknom in the Chrome Store) to AMO and see what errors I get. I'll document them here 😄 

-----
Some info about Chrome extensions not working in Firefox is here, the info might help: https://public.etherpad-mozilla.org/p/webextensions-bugs

-----
* [x] Accept ZIP uploads in "Submit a new Add-on" (https://github.com/mozilla/addons-server/issues/2727)
* [x] Allow line comments in `addons-linter` (https://github.com/mozilla/addons-linter/issues/723)
* [x] Allow line comments in `addons-server` (https://github.com/mozilla/addons-server/issues/2734)
* [x] ~~Remove `update_url` from add-ons in `addons-server` (https://github.com/mozilla/addons-server/issues/2835)~~
* [x] Deal with `update_url` better in `addons-linter` (https://github.com/mozilla/addons-linter/issues/726)
* [x] Accept CRX uploads in "Submit a new Add-on" (#2726)
* [x] Parse CRX files in `addons-linter` (https://github.com/mozilla/addons-linter/issues/696)

**Comment by tofumatt** [comment]
Everything is checked off. Gonna call this one done!
