### ISSUE TITLE
Reduce the number of unpackaged/forked dependencies

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#2870]
In [requirements/prod_without_hash.txt ](https://github.com/mozilla/addons-server/blob/master/requirements/prod_without_hash.txt) we've got 10 or so dependencies that are pulled directly from github.

This sucks, slows down package creation/tests, etc. Let's try to reduce that to 0 by:
- Landing our forks patches upstream 
- Using released packages
- Removing dependencies on weird or unmaintained code

**TODO:**
- [x] django-queryset-transform (#2963)
- [x] django-tables (#2578)
- [x] happyforms (#2964)
- [x] schematic (#2863)
- [x] jingo-minify
- [x] django-moz-header (#2984)
- [x] nuggets (#2965)
- [x] django-session-csrf  (#2956)
- [ ] django-cache-machine
- [x] django-uuidfield (gone in django 1.8 merge, see 7d2a98f)
- [ ] django-mobility https://github.com/mozilla/addons-server/issues/5055

**Comment by andymckay** [comment]
django-uuidfield can probably be replaced with https://docs.djangoproject.com/en/1.9/ref/models/fields/#uuidfield anyway once we get to django 1.8.

**Comment by diox** [comment]
Yes, I wonder how straightforward the change will be though...

**Comment by EnTeQuAk** [comment]
Since we're using MySQL afair both use a similar way to store them so they are relatively compatible. It's a bit more complicated with postgres where django's uuidfield uses the builtin uuid field type.

**Comment by EnTeQuAk** [comment]
Regarding happyforms: https://github.com/mozilla/addons-server/issues/1569

**Comment by EnTeQuAk** [comment]
And we don't use too much stuff from it.

```
src/olympia/lib/settings_base.py
412:    'moz_header',
490:            'moz_header/header.css',
491:            'moz_header/footer.css',
507:            'moz_header/header.css',
508:            'moz_header/footer.css',
679:            'moz_header/menu.js',

Binary file src/olympia/lib/settings_base.pyc matches.

src/olympia/templates/menu_links.html
1:{% extends "moz_header/menu_links.html" %}

src/olympia/templates/amo_footer.html
1:{% extends "moz_header/footer.html" %}

src/olympia/templates/copyright.html
1:{% extends 'moz_header/copyright.html' %}
```

But still, might some more grebbing and searching and trying...

**Comment by andymckay** [comment]
"more grebbing" 👍

**Comment by andymckay** [comment]
https://github.com/search?langOverride=&q=user%3Amozilla+django-moz-header&repo=&start_value=1&type=Code looks like almost no-one else uses it either. Just copy the stuff into src/olympia?

**Comment by diox** [comment]
> Since we're using MySQL afair both use a similar way to store them so they are relatively compatible. It's a bit more complicated with postgres where django's uuidfield uses the builtin uuid field type.

I was more thinking about conversions from/to python. The fork of django-uuidfield we use has this code https://github.com/andymckay/django-uuidfield/commit/029dd1263794ec36c327617cd6c2346da81c8c33 which is incompatible with the way upstream does things, so I'll bet we'll need to be extra careful when moving to the django's implementation.

**Comment by diox** [comment]
Regarding django-moz-header, one of the contractors working on AMO at the time opened https://github.com/mozilla/django-moz-header/pull/20 but it never got merged, I assume because everyone is scared to modify this repos... I agree we should probably just copy it over.

**Comment by eviljeff** [comment]
shall we just merge django-mobility directly into olympia, stripping out anything unused?

**Comment by eviljeff** [comment]
btw, I filed #2578 for django-tables

**Comment by EnTeQuAk** [comment]
Started to push things upstream for cache-machine, https://github.com/django-cache-machine/django-cache-machine/pull/120

**Comment by diox** [comment]
> https://github.com/search?langOverride=&q=user%3Amozilla+django-moz-header&repo=&start_value=1&type=Code looks like almost no-one else uses it either. Just copy the stuff into src/olympia?

Agreed, I'll do that.

**Comment by diox** [comment]
Ended up removing django-moz-header entirely cause it was barely used.

**Comment by diox** [comment]
We've reduced it to 2. django-mobility will go away in #5055 and cache-machine... well, that's a story for another issue. Let's close this.
