### ISSUE TITLE
Remove FxA migration and unused password code

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3049]
Once we have flipped the migration waffle off we can remove a lot of code.

Remove the migration waffle since we're never going back.

Drop the password column if possible and update anything that is expecting a password (`make initialize_docker` and change password, for example). If the password column cannot be dropped it should at least be set to unusable passwords and support for setting passwords on users should be removed.

* [x] Remove migration waffle.
* [x] Remove login view.
* [x] Remove change password code.
* [x] Remove forgot password code.
* [x] Remove blacklisted password.
* [x] Remove blacklisted email code.
* [x] Remove change email code.
* [x] Remove user registration, confirmation and all code dealing with `confirmationcode`.
* [x] Remove password from "super-create" user API.
* [x] Update `./manage.py createsuperuser`.
* [x] Update `self.client.login()` calls.
* [x] Remove password code from model and tests and any settings (like `PASSWORD_HASHERS`).
* [x] Remove `fxa-migrated` waffle and `user.fxa_migrated()`.
* [x] Remove fxa mail in zadmin forms/views.
* [ ] ~~Remove password and confirmationcode column/data~~ (#3746).
* [ ] ~~Move some accounts code into an authentication backend~~ (#3799).
* [ ] ~~Update documentation about 3rd party AMO support~~ (#3867).
* [x] Any unused JS

**Comment by diox** [comment]
2 more *potential* things to remove / update that I'm not sure of:
- New user confirmation and all code dealing with `confirmationcode`
- Email change views

How do these work with FxA ? Do they need to be removed completely ?

**Comment by mstriemer** [comment]
Thanks, I've updated my list.

There's currently no way to change your email address since FxA does not support it and we have no way of switching to a different Firefox Account.

**Comment by mstriemer** [comment]
QA: There's no real STR here since it's just removing code that isn't being used. It would be good to verify that there aren't any regressions around signing up, signing in or editing a user though.

**Comment by ValentinaPC** [comment]
While testing around registration I saw that entering an already created account in the "Create a New Account" page, does no longer return a "The account already exists. Please Sign in" message, is this intended?
This is happening all around AMO servers... so I think is not a regression.

**Comment by mstriemer** [comment]
@ValentinaPC If you use the same email and password as an existing account to register for FxA it should just log you in. If the password doesn't match it should prompt to sign in instead.

**Comment by ValentinaPC** [comment]
Entered the same e-mail but different password, and the "Sign in" message was displayed as you said. 
![2016-09-26_1850](https://cloud.githubusercontent.com/assets/15685960/18841459/835d0c96-841a-11e6-809f-13237bb83e5a.png)

Tested around: registration, account update, log in, and no issues were found.
Marking this as verified.

**Comment by mstriemer** [comment]
Remaining work broken out into separate issues.
