### ISSUE TITLE
Support submitting Listed and Unlisted versions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3465]
This is a tracker bug for the tasks needed to support submitting Listed and Unlisted versions as specified in [this PRD](https://docs.google.com/document/d/1v32JqoLcn_6MfviFXOY0UTq-tigifTllL3yOUyn0-1M/edit). Here are the steps that we need for this (I'll file individual bugs):
1. [x] Add `channel` field to `version` and set it on version submission. #3466
2. [x] Set `channel` for all existing add-on versions. #3467
3. [x] Communicate changes to developers and update documentation. (Jorge) 
4. [x] Use `channel` to determine version visibility. #3567
5. [x] Update editor tools to handle unlisted and listed versions. #3989
5. [x] Enable channel selection on submission.
   1. [x] New add-on submission flow. #3468
   2. [x] New version update submission flow. #3469 
      1. [x] New file update submission flow. #3948
   3. [x] Show channel in Status & Versions page. #3470
   4. [x] Update add-on visibility box and status sidebar. #3471
6.  [x] Hide unneeded developer options when only unlisted versions have been submitted. #3472
7. [x] Cleanup: 
   1. [x] Don't reference `is_listed` in non test code #3977
   2. [x] Remove old inline version/file upload #4076
   3. [x] Remove `is_listed` from `addon`. #3473

**Comment by diox** [comment]
(Edited description to turn this into a TODO list with links, so that we can easily find out what we have done and what is left, in order)

**Comment by eviljeff** [comment]
Everything done, bar a few [bugs ](https://github.com/mozilla/addons-server/labels/version%20channel)we'll fix, so closing.
