### ISSUE TITLE
[tracker] Switch to django-migrations

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#3705]
This is the overall tracking issue to manage progress on switching to Django's builtin migrations framework.

We are currently using https://github.com/mozilla/schematic/ which is a very simplified migrations script which leads to writing plain SQL migrations and having a hard time with data migrations and lots of one-off scripts.

(copied from https://github.com/mozilla/addons-server/issues/3705#issuecomment-471957170)
* [x] Make sure the dev, stage and prod database schema are mostly identical (#10916)
* [x] Then make sure we are able to generate a schema locally that looks like -dev, or go the other way around and implement a migration that migrates -dev, -stage and -prod to something like -local. I haven't looked too deep into this so I can't really say which may be more complicated (#10917) 
* [x] Then switch to django-migrations :) (#12333)
  * Add initial migrations
* [x] Remove old migrations files  (#12390)

**Comment by EnTeQuAk** [comment]
Some updates on this. There are a few steps required to actually get there.

* Make sure the dev, stage and prod database schema are mostly identical
* Then make sure we are able to generate a schema locally that looks like -dev, or go the other way around and implement a migration that migrates -dev, -stage and -prod to something like -local. I haven't looked too deep into this so I can't really say which may be more complicated
* Then switch to django-migrations :)
 * Add initial migrations and maybe even use that to migrate schema changes required in step 2 
* Remove old migrations files

Attached you'll find schema exports from Nov 30th 2018 which give you a hunch of what differences there are. Most are already fixed at this time afaik.

With us being on Django 1.11 we can add [custom indexes](https://docs.djangoproject.com/en/1.11/ref/models/indexes/) which hopefully cover most of our use-cases.

[prod_schema.txt](https://github.com/mozilla/addons-server/files/2956506/prod_schema.txt)
[stage_schema.txt](https://github.com/mozilla/addons-server/files/2956507/stage_schema.txt)
[dev_schema.txt](https://github.com/mozilla/addons-server/files/2956508/dev_schema.txt)

**Comment by eviljeff** [comment]
copied the steps to the top comment with checkboxes and filed https://github.com/mozilla/addons-server/issues/10916 and https://github.com/mozilla/addons-server/issues/10917 for the first two steps

**Comment by diox** [comment]
To make sure migrations are backwards-compatible, making them less painful to deploy, this post and the apps linked in it are super useful: https://medium.com/3yourmind/keeping-django-database-migrations-backward-compatible-727820260dbb

**Comment by diox** [comment]
We made the switch.
