### ISSUE TITLE
API changes with the introduction of version channels

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3922]
Parent: #3567

Some changes are required in the addons API with the introduction of version channels. This affects so-called "unlisted" add-ons, because when we are done, that concept won't exist anymore, we'll have unlisted/listed *versions* instead.

Breakdown of the changes I'm thinking about:
* [ ] `{addon}.is_listed` will be removed
* [x] `{addon}.current_version` will point to the latest *listed* public version (see #3847)
* [x] `{addon}.latest_unlisted_version` will be introduced, and point to the latest *unlisted* version as the name implies. It should only be shown to the add-on owner, or in the internal API. It will need to be added to the ES index. (#3945)
* [x] Addons without a `current_version` will be excluded from public search results (but included in internal search) - we'll filter on that instead of `is_listed`. This has an impact on non-API legacy search code as well. (#3969)

**Comment by eviljeff** [comment]
Would be a separate issue, but the submission (signing) API needs updating to support channels too
