### ISSUE TITLE
Implement Add-ons Post-Review Process

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5211]
This is a tracking bug for implementing Add-ons post-review process.

Essentially post-review is the follow-up of https://github.com/mozilla/addons-server/issues/4533 : the goal is to automatically approve WebExtensions without human intervention ; human reviews are done after the add-on has been pushed to public, prioritized depending on various factors.

* PRD: https://docs.google.com/document/d/1hVx-NbuVRc0wKXSdt8eHceObexY93YFzMXtqYC95nUs/edit
* Implementation plan with what we care about for Q2: https://docs.google.com/document/d/1rZvM2QGk8WtkNUDRvLEvrbqZ190hvHfOle4zVRllQmw/edit
* Post-review weights for prioritization https://docs.google.com/spreadsheets/d/1CZEECHHqEmK87fNiWNslAsFQBL7zxYF-c63-zZVZuqw/edit#gid=0

Steps:
1. [x] Deploy current auto-approval implementation (which auto-approves a fraction of WebExtensions *updates* that match some criteria) #5155, #4533
2. [x] Implement list of auto-approved add-ons in reviewer tools #5154
3. [x] Allow human reviewers to confirm approval of automatically approved add-ons (or reject them), tweak reviewer tools to display abuse reports etc more prominently. #5258
4. [x] Post-review list prioritization with risk factors evaluation. #5473 
5. [x] Add static flags analysis to the risk factors used for prioritization. #5475
6. [x] Submission process updates. #5579
7. [x] Remove auto-approval restrictions, making all WebExtensions that pass validation auto-approved automatically. #5665

**Comment by diox** [comment]
Random showerthought: Once post-review is live in production and works well, *maybe* we could:
- Remove the `auto_approve` cronjob and the concept of awaiting review - make everything public right away. `STATUS_AWAITING_REVIEW` would go away.
- Simplify `AutoApprovalSummary`, removing all conditions and the concept of `verdict`, leaving only weight computation, and call it automatically at upload time

The only thing stopping us to do that is support for other kind of add-ons that might still need the review process. (search engines ? dictionaries ? language packs ?)

**Comment by jvillalobos** [comment]
> make everything public right away

For WebExtensions add-ons, that's the expectation, yes.

Like you point out, there are still legacy add-ons (including new ones that support Thunderbird and SeaMonkey), and non-extension types. Complete themes should probably still be reviewed, but I wouldn't mind moving search engines, dictionaries, and language packs to a post-review model, since their risk is very small. @wagnerand and @kewisch should weigh in on this.

**Comment by wagnerand** [comment]
Sounds good to me. Do we sign all of them?

**Comment by jvillalobos** [comment]
We sign dictionaries, language packs, and complete themes. Search engines are still only an XML file.

**Comment by diox** [comment]
Still some minor things to implement in other issues but the main tasks this issue is tracking are done.
