### ISSUE TITLE
Reviewer tools adjustments for post-review

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5258]
For reviewers with `Addons:PostReview` permission, **if the last version of the add-on they are looking at has been automatically approved**, the review page needs to:

* [x] Display recent user ratings and abuse reports in reviewer tools #5272
* [x] Display recent abuse reports about developers of add-ons in reviewer tools #5310
* [x] Have ability to store reviewer approval for auto-approved add-ons #5273
* [x] Have the *Request super-review* action stop sending an e-mail to the developer #5274
* [x] Have the *Reject* action include a way to select which versions of the add-on are affected by the rejection. All of those versions should be disabled once the review is saved, and should be listed in the email sent to the developer. #5275

In addition, regardless of the state of the last version, a bonus for QA/devs debugging:
* [x] Display auto approval summary next to unreviewed versions #5294

**Comment by diox** [comment]
PRD calls for mocks but it's probably not necessary. The new new rejection email template is needed however.

**Comment by diox** [comment]
All dependencies fixed, closing this tracking bug.
