### ISSUE TITLE
use npm for our libs

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5458]
Security! Prosperity! 

Contents of /lib/ that we need to migrate to using npm:

- [x] jqModal.js  #5702
- [x] jquery-ui #5580 
  - jquery-ui\autocomplete.js
  - jquery-ui\core.js
  - jquery-ui\datepicker.js
  - jquery-ui\menu.js
  - jquery-ui\mouse.js
  - jquery-ui\position.js
  - jquery-ui\sortable.js
  - jquery-ui\widget.js
- [x] jquery-1.12.0.js #5571
- [x] jquery.browser.js #5585
- [x] jquery.cookie.js #5585
- [x] jquery.minicolors.js  #5713
- [x] jquery.pjax.js ~#5585~ reverted in #5678 now #5717
- [x] jquery.timeago.js #5585
- [x] less.js #5586
- [x] raven.min.js  ~#5698~ #5705
- [x] underscore.js #5659
_Consciously skipping_
- [ ] syntaxhighlighter  (https://www.npmjs.com/package/syntaxhighlighter; would be a major update)
  - syntaxhighlighter\shBrushCss.js
  - syntaxhighlighter\shBrushJava.js
  - syntaxhighlighter\shBrushJScript.js
  - syntaxhighlighter\shBrushPlain.js
  - syntaxhighlighter\shBrushXml.js
  - syntaxhighlighter\shCore.js
  - syntaxhighlighter\shLegacy.js
- [ ] highcharts.src.js   (https://www.npmjs.com/package/highcharts; huge package and may be a significant update)
_Deleted_
- [x] ~amd.js #5572~
- [x] ~csrf.js #5572~
- [x] ~flipsnap.js #5572~
- [x] ~jqmobile.js #5572~
- [x] ~moment-with-langs.min.js #5572~
- [x] ~uri.js #5572~
_Not on NPM_
- [x] diff_match_patch_uncompressed.js
- [x] format.js
- [x] jquery.hoverIntent.js
- [x] jquery.zoomBox.js
- [x] ngettext-overload.js (is unneeded in Django 1.10+ too)
- [x] popcorn-1.0.js
- [x] truncate.js
- [x] ui.lightbox.js (original host and project page is gone)

**Comment by eviljeff** [comment]
calling this done as the only remaining libs in js/lib/ are either:
- our own home-baked library code
- aren't on NPM
- are too complicated and too niche to justify the effort (syntaxhighlighter and highcharts)
