### ISSUE TITLE
Implement new post-review weights

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6033]
Follow-up of https://github.com/mozilla/addons-server/issues/5475 : some new weights need to be implemented once the linter supports them.

Need to follow this list: https://github.com/mozilla/addons-linter/issues?utf8=%E2%9C%93&q=label%3A%22project%3A%20auto%20approval%22%20

We need:
* [x] <script> tag with a remote URL - mozilla/addons-linter#1321 (weight: 40)
* [x] Violate the Mozilla Conditions of Use - mozilla/addons-linter#1285 (weight: 20)
* [x] Libraries and other unreadable code - mozilla/addons-linter#1323 (weight: 10)
* [x] Size of code changes - mozilla/addons-linter#1304 
  * [x] + some code to compare with the previous public version #6330

In addition, those would be nice to have, but not blocking this issue:
* Plain HTTP for sensitive operations - mozilla/addons-linter#259
* Synchronous (non-local) HTTP requests - mozilla/addons-linter#1322
* Require permissions that are not used - mozilla/addons-linter#1286
