### ISSUE TITLE
Simplify Contributions feature

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6069]
This is a tracking issue for the changes to the Contributions feature, as specified in [this document](https://docs.google.com/document/d/1DjXQbl_hZlRe4bqE9B-cLPfq64wYFa19TU9DfsOpckQ/edit?ts=597f51b1#).

- [x] [Product] Ask developers for domains they would like to use for contributions.
- [x] Add a Contributions URL field in the developer tools. #6070
- [x] [Product] Notify developers so they can fill in the new field.
- [x] Change Contribute section in listing pages (old front-end). #6071
- [x] Change data sent in Add-ons Manager (legacy) API. #6308
- [x] Expose Contributions URL in Addon (v3) API. #6434
- [x] Remove Developer Profile and Roadblock pages. #6072
- [x] Remove Manage Developer Profile and Manage Payments sections in devhub. #6073
- [ ] Remove Contributions section from developer statistics dashboard. #6074
- [ ] Additional cleanup (Paypal code, unused DB fields). #6076
- [ ] Implement UI on new frontend (https://github.com/mozilla/addons-frontend/issues/3149)

This opening comment will be updated as the plan evolves.

**Comment by gravyboat** [comment]
This is a great feature for those of us who refuse to work with PayPal, thanks for the thorough issue and associated documentation.

**Comment by eviljeff** [comment]
@jvillalobos can you log an issue for "Change data sent in Add-ons Manager API."?  I don't understand what needs to be done/changed.

**Comment by jvillalobos** [comment]
It's explained in the PRD and is awaiting review by @mstriemer. We just need to see what checks are in place in the Add-ons Manager side to decide what we can change without breaking backward compatibility.

**Comment by muffinresearch** [comment]
Would be good to explicitly instrument the links so that we know that they're being used.

**Comment by mstriemer** [comment]
I added some comments to the Google Doc. It looks link `meet_developers` is required in `contribution_data`, `link` is unused and `suggested_amount` will be shown it if it is present.

I don't see anything validating what `meet_developers` points to. It look like it can be an arbitrary URL, which may or may not be a good thing.

**Comment by eviljeff** [comment]
If link is unused but meet developers is used then we can either send the contribution url as `meet_developers` or have `meet_developers` just go to the listing page.  Suggested amount won't be used any more.

**Comment by eviljeff** [comment]
@jvillalobos when are you planning to notify users (and plan to eventually flip the switch)?

**Comment by jvillalobos** [comment]
They were notified this week and I gave them a month to update. Let's schedule this to go live on October 11th, if everything's in place by then.

**Comment by eviljeff** [comment]
All the work pre-waffle-switch-enabling is done now, afaik.  
QA:
This will need some testing on -dev with some known add-ons that have existing paypal contributions set up.  
Three rough scenarios:
A) Add-on that had paypal contributions enabled and doesn't have simple contributions set up
B) Add-on that had paypal contributions enabled and has simple contributions setup
C) Add-on that didn't have paypal contributions enabled, but has simple contributions set up

Bonus marks for a range of add-ons supporting the different settings ['Only ask on this add-ons page and developer profile'; 'Ask after users start downloading this add-on'; 'Ask before users can download this add-on'].  The latter two settings are the most invasive and changed the installation flow.

After the `simple-contributions` waffle is enabled there shouldn't be any roadblock to installation, or references to the old contributions* - there should only be the contribute button on the detail page for add-ons that have it set up.

 * The statistics page will retain references to the old contributions feature for a few weeks more.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF58 (Win 7).
Example:
https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/

> A) Add-on that had paypal contributions enabled and doesn't have simple contributions set up

- accessing its review page - https://addons-dev.allizom.org/en-US/editors/review/awesome-screenshot-plus- - we can see the Contribute button still there
- accessing about:addons - Extensions tab after install, will list Contribute button (clicking on contribute button will load a stage page.... weird stage page - https://addons.allizom.org/en-US/firefox/addon/awesome-screenshot-capture-/developers?src=api)
- Dev Hub does not list any old payment page

> B) Add-on that had paypal contributions enabled and has simple contributions setup

If using same example, but enabling the  simple contribution setup in Dev Hub will change the looks and behavior only in add-on details page. 
Reviewer Tools and about:addons cases remain and behave as above.
Clicking on Contribute button from add-on details page, will load the indicated URL from Dev Hub, using "outgoing.stage..." service - don't know if ok?

> C) Add-on that didn't have paypal contributions enabled, but has simple contributions set up

This case is working as expected.


> Bonus marks for a range of add-ons supporting the different settings ['Only ask on this add-ons page and developer profile'; 'Ask after users start downloading this add-on'; 'Ask before users can download this add-on']. The latter two settings are the most invasive and changed the installation flow

Disabled the flag, submitted webextension for all 3 cases, and re-anabled the contrib flag, and obtained the following results:
 
1. **"Only ask on this add-ons page and developer profile"** - https://addons-dev.allizom.org/en-US/firefox/addon/webext-oldcontrib-case0/ - Everything looks ok in add-on details page. Contribution in about add-on with redirection to a 404 page (https://addons-dev.allizom.org/en-US/firefox/addon/webext-oldcontrib-case0/developers?src=api), Contribution in review page, working as before.

2. **"Ask after users start downloading this add-on"** - https://addons-dev.allizom.org/en-US/firefox/addon/webext-ondcontrib-case-1/ - Everything looks ok in add-on details page. Behaving like above case.

3. **"Ask before users can download this add-on"** - https://addons-dev.allizom.org/en-US/firefox/addon/webext-oldcontrib-case2/ - Everything looks ok in add-on details page. No Contribution button in about:addons, but still listed and working in review page.

@eviljeff : Please forgive the long reply and let me know if you have questions and what do you think. Thanks!

**Comment by eviljeff** [comment]
@ValentinaPC 
Thanks for the testing!  If I'm parsing your reply properly the problems you found are:
- old contribution button/feature on editors review page
- about:addons is not working.  (that was done in #6308)
- anything else?

I don't care too much about the editors review page - no-one is going be donating through there, it's an historical anomaly that it's there at all.  It will be removed in the post waffle clean-up if I don't get to it before.

about:addons is a strange one.  is the url set locally to dev?  (stage is updated too now, as I write this)  `extensions.getAddons.search.url` or `extensions.getAddons.get.url` I think.

**Comment by ValentinaPC** [comment]
So, the about:addons part looks good now.
For all 3 examples above, no Contribution button is displayed in about:addons.
We still display the contribution button in Reviewer Tools, but we are ok with that.

Based on recent testing an above comments, we can mark this verified fixed.

**Comment by jvillalobos** [comment]
As planned, the switch has been turned on today.
