### ISSUE TITLE
[Tracker] Updating Reviewer Recognition Program 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#6454]
This is a tracking issue for changes to the reviewer recognition program as specified in [this document](https://docs.google.com/document/d/1O-dOi_PafpOpZ7SWPpKUK7qs5ARkS0CMCP5xpJfDrDE/edit#). 

**Queue Modifications**
- [x] Do not expose extensions in lowest risk factor range  -- issue #6472 
[_Note: range to be determined once feature is turned on in prod_]

**Points System Modifications**
- [ ] Add new reviewer behaviors and assign points -- Issue #6473
_Note: point values subject to change_

**Reporting**
- [ ] Set up automated quarterly reporting with reviewer's ID, reviewer's name, number of add-ons reviewed that quarter, and number of points achieved that quarter. Report can come as a .csv or .xls file, or be dropped into a Google sheet. -- Issue #6474

**To Be Determined**
- [ ] Associating add-on risk factor ranges with reviewer behaviors

**Comment by jvillalobos** [comment]
I'm creating a separate tracker for review tools work in Q4, where I'll include #6474. #6473 is now a P2 and is being tracked with the other post-review followups. Therefore I'm closing this tracking issue.
