### ISSUE TITLE
Reviewer tools work for Q4

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6520]
This is tracking bug for the reviewer tools work planned for Q4.
- [ ] Send quarterly report for reviewer activity. #6474
- [x] Color weights in auto-approved queue. #6518
- [x] Unified reviewer dashboard. #6522
