### ISSUE TITLE
Review process updates

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7172]
This is a tracker for the changes to be done to the existing reviewer tools, as specified in the [Reviewer Tools PRD](https://docs.google.com/document/d/1Me-2Qx-C7cMptKQt_-1gAyPZCBOiww9laQLEMlD9N2M/edit). These changes will be done in the existing tools because the UX and architectural redesign work is a longer term project that will be tackled in phases, and these changes are a more immediate need.

- [x] Create a `Reviewers: Admin` group with `Reviews:Edit` permission. #7279
- [x] Add a `Reviewer Tools` item to the user dropdown on AMO, pointing to the dashboard. #7280
- [x] Create "More Actions" section in review pages #7282
  * Add toggle to be notified about all future listed updates.
  * Unflagging for admin review.
  * Disable listing.
- [x] Add a deadline for requests for information. #7283
- [x] Disable auto-approval of future listed versions. #7284

**Comment by wagnerand** [comment]
> Replace notes to reviewer with whiteboard during submission.

Are we going to remove the "Notes to Reviewers" in favor of the Whiteboard?

I agree having both can be confusing at times, although both of them have their (distinct) purpose. What I don't like about the current whiteboard implementation is that there is no history, which is especially important if we're going to remove "Notes to Reviewers". Maybe we should hold off on this specific change and come up with a better solution, while we're at changing things.

**Comment by jvillalobos** [comment]
Having both is confusing for developers, and the Whiteboard seems to be the most practical of the two. Agree it would be useful to keep a log of when the Whiteboard is updated, so it's knowable whether it changed recently or not. Storing all previous versions of the Whiteboard would essentially turn it into Notes to Reviewer, though, so I would prefer to avoid going that far.

**Comment by wagnerand** [comment]
> Create a Reviewers: Admin group with ReviewerAdminTools:View and Reviews:Edit permissions.

I just noticed that you need to have `Addons:Edit` in order to view attached source code, which is what admins need.

**Comment by jvillalobos** [comment]
Yeah, that line isn't clear. I'll clarify in the dependent issue, but the intention is to create that permission and gate admin reviewer stuff behind it. `Addons:Edit` is fairly broad, and I think everyone in `Staff` currently have it.

**Comment by wagnerand** [comment]
Ah, yes, that sounds favorable.

**Comment by diox** [comment]
Nothing left to do here, the last bit landed last week.
