### ISSUE TITLE
AMO Admin Tools, phase 1

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7176]
This is a tracker for the implementation of the first phase of the AMO Admin Tools, as specified in the [Admin Tools PRD](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit). This first phase focuses on setting up the basic framework (permission groups, index) and the tools required for homepage curation and spam mitigation.

- [ ] Give the `System Administrators` group a new `All:Admin` permission that will gate all admin features specified in the PRD as Full admin tools. #7249
- [x] Create a `Curators` group with a new `Content:Curate` permission that will gate all features specified in the PRD as Content curator tools. #7250
- [x] Add an `Admin Tools` item to the user dropdown on AMO, pointing to an index of available admin tools. #7251
- [ ] [Blocked text content](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit#heading=h.hs3rkqx0bfty). #7252
- [ ] [User admin](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit#heading=h.b7y5z7x7pzhe): show all content for user, banning, deleting. #7268
- [x] [Replacement add-ons](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit#heading=h.3wbd4ya878ev). #7253
- [ ] [Homepage content curation](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit#heading=h.wi0zo8c4banm). #7261

**Comment by dessant** [comment]
Please share public PRDs whenever possible, there are a number of non-public docs linked in issues and casual readers miss a lot of context as a result.

**Comment by jvillalobos** [comment]
Sure thing.

**Comment by diox** [comment]
I've replaced this tracking issue by a project: https://github.com/mozilla/addons-server/projects/2
