### ISSUE TITLE
Tracker: Update reviewer messages to developer 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#7352]
Tracking issue to update messages to developers from AMO. 

- [x] Update template for "more information requested" email (issue #7366 )
- [x] Update template for "your add-on has been rejected" email (issue #7369)
- [x] Add new canned response for "your add-on has been disabled due to a lack of response for additional information requested" (issue #7370 )
- [x] Update canned response for "incomplete description" action (issue #7367)
- [x] Prefix subject of review emails (#7427)
- [x] Update template for "successful submission to AMO" email (issue #7478)
- [x] Update template for "updated add-on" email (issue #7469) 
- [x] Update template for signing unlisted extensions (issue #7724) 
- [ ] Update end block template

**Comment by diox** [comment]
@caitmuenster can we close this ?

**Comment by caitmuenster** [comment]
Closing it now!
