### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9105]
This is a meta-issue (where a github project would be overkill) to track our progress towards Python 3.

With us now using Django 1.11, this is the next logical step besides django-migrations towards a better future.

The general idea is that we should support Python 2 and Python 3 in the addons-server code-base so that we may even be able to run them side-by-side to issue a staged-rollout to reduce risk.

- [ ] #4997 Make sure dependencies support python 2 and 3 (this will probably require a split between some py2/py3 only dependencies at some point)
- [x] Add a travis stage build config that runs Python 3 tests with `allow_failures:` set properly
- [x] Make sure that stage build config runs tests but will most certainly fail some (many) tests
- [ ]  Use `six.text_type` instead of `unicode` #10327
- [ ] Use `six.moves.urllib_parse` instead of `urlparse` #10328

**Comment by EnTeQuAk** [comment]
side note: We'll want to use https://pypi.org/project/tox-travis/ to seamlessly switch between python 3 and 2 on travis/tox

**Comment by diox** [comment]
3 things currently prevent our tests from running properly and discovering actual issues:
- #10327, because `unicode` doesn't exist in Python 3.
- #10328, because`urlparse` has been moved in Python 3.
- `supervisor` dependency not being compatible (prevents the `assets` job from running as it installs dev dependencies)

**Comment by diox** [comment]
Closing this in favor of the project: https://github.com/orgs/mozilla/projects/55
